[smartstore]
title = "네이버 스마트스토어 ─ 미러볼뮤직"
url = "https://smartstore.naver.com/mirrorballmusic/category/ALL?cp=1"
entrySelector = "ul li.-qHwcFXhj0"
titleSelector = "strong.QNNliuiAk3"
linkSelector = "a"
imageSelector = "img._25CKxIKjAk"
contentSelector = "div._23DThs7PLJ span.nIAdxeTzhx"
waitUntil = "networkidle"